#!/usr/bin/env bash
# Xcode Cloud: runs automatically before `xcodebuild` when present at
#   <repo>/ci_scripts/ci_pre_xcodebuild.sh
#
# Why: project.yml baseConfigurationReference is App/iOS/Secrets.xcconfig,
# which is gitignored (local secrets). Cloud must materialize that file from
# Environment Variables set in App Store Connect → Xcode Cloud → Environment.
#
# Required env vars (set in Xcode Cloud, Secret type recommended):
#   SUPABASE_URL
#   SUPABASE_PUBLISHABLE_KEY   (alias: SUPABASE_ANON_KEY)
# Optional:
#   YELP_API_KEY
#   TICKETMASTER_API_KEY
#
# Local developers: use ./scripts/sync-secrets-from-mastermind.sh instead.
set -euo pipefail

ROOT="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/.." && pwd)}"
XCCONFIG="$ROOT/App/iOS/Secrets.xcconfig"

URL="${SUPABASE_URL:-https://dvomzrvslwdabwcwtvrg.supabase.co}"
KEY="${SUPABASE_PUBLISHABLE_KEY:-${SUPABASE_ANON_KEY:-}}"
YELP_KEY="${YELP_API_KEY:-}"
TM_KEY="${TICKETMASTER_API_KEY:-}"

if [[ -z "$KEY" ]]; then
  echo "error: SUPABASE_PUBLISHABLE_KEY (or SUPABASE_ANON_KEY) is not set in the Xcode Cloud environment." >&2
  echo "  App Store Connect → your app → Xcode Cloud → Settings → Environment" >&2
  echo "  See docs/ship/XCODE-CLOUD-SECRETS.md" >&2
  exit 1
fi

# xcconfig treats // as a comment — raw https:// truncates to "https:"
# (build 23 regression). $() breaks the slashes safely.
XCCONFIG_URL="$(printf '%s' "$URL" | sed 's|https://|https:/$()/|')"

mkdir -p "$(dirname "$XCCONFIG")"
cat >"$XCCONFIG" <<EOF
// Generated by ci_scripts/ci_pre_xcodebuild.sh — DO NOT COMMIT
SUPABASE_URL = $XCCONFIG_URL
SUPABASE_PUBLISHABLE_KEY = $KEY
YELP_API_KEY = $YELP_KEY
TICKETMASTER_API_KEY = $TM_KEY
EOF

# Readable by the build, not world-writable
chmod 600 "$XCCONFIG"

echo "✓ Wrote $XCCONFIG from Xcode Cloud environment variables"
# Do not print secret values
echo "  SUPABASE_URL set: $([[ -n "$URL" ]] && echo yes || echo no)"
echo "  SUPABASE_PUBLISHABLE_KEY set: yes (length ${#KEY})"
echo "  YELP_API_KEY set: $([[ -n "$YELP_KEY" ]] && echo yes || echo no)"
echo "  TICKETMASTER_API_KEY set: $([[ -n "$TM_KEY" ]] && echo yes || echo no)"
