#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
TOTAL_MINUTES=15

# Write targets (override via env if your layout differs).
REPO="${MANGASM_REPO:-$HOME/mangasm}"
SECRETS_ENV="${MASTERMIND_SECRETS:-$HOME/mastermind-ai/secrets.env}"
WEB_ENV="$REPO/web/.env.local"
SUPABASE_PROJECT_REF="dvomzrvslwdabwcwtvrg"
mkdir -p "$(dirname "$SECRETS_ENV")" "$REPO/web"

banner "Mangasm secrets setup"

# ── Stage 1: Supabase publishable key → mastermind secrets.env ────────────
ENV_FILE="$SECRETS_ENV"
stage "Supabase — publishable key" 3
say "The iOS app reads Supabase from your mastermind secrets file:"
note "$SECRETS_ENV"
open_url "https://supabase.com/dashboard/project/$SUPABASE_PROJECT_REF/settings/api"
step "Under 'Project API keys', copy the anon / publishable key (safe for client apps)."
warn "Do NOT copy the service_role / secret key — that must never ship in the app."
ask_secret MANGASM_SUPABASE_PUBLISHABLE_KEY "Paste the anon / publishable key:"
write_env MANGASM_SUPABASE_PUBLISHABLE_KEY "$MANGASM_SUPABASE_PUBLISHABLE_KEY"
note "SUPABASE_URL defaults to https://$SUPABASE_PROJECT_REF.supabase.co (already correct)."

# ── Stage 2: Yelp Fusion API key ──────────────────────────────────────────
stage "Yelp Fusion — API key (DateNight restaurants)" 3
open_url "https://www.yelp.com/developers/v3/manage_app"
step "Sign in. If you have no app yet, create one (any name/website is fine)."
step "Copy the 'API Key' value — the long token, NOT the Client ID."
ask_secret YELP_API_KEY "Paste the Yelp API Key:"
write_env YELP_API_KEY "$YELP_API_KEY"

# ── Stage 3: Ticketmaster API key ─────────────────────────────────────────
stage "Ticketmaster — API key (DateNight events)" 3
open_url "https://developer.ticketmaster.com/user/me/apps"
step "Sign in → My Apps → open your app (or add one)."
step "Copy the 'Consumer Key' — that is your API key."
ask_secret TICKETMASTER_API_KEY "Paste the Ticketmaster Consumer Key:"
write_env TICKETMASTER_API_KEY "$TICKETMASTER_API_KEY"

# ── Stage 4: Sync captured keys into the iOS build config (action) ────────
stage "Sync keys into the iOS build" 1
say "Generates App/iOS/Secrets.xcconfig + supabase/.env.local (both git-ignored)."
if confirm "Run sync-secrets-from-mastermind.sh now?"; then
  if MASTERMIND_SECRETS="$SECRETS_ENV" bash "$REPO/scripts/sync-secrets-from-mastermind.sh"; then
    say "${GREEN}✓ synced${RESET} — Secrets.xcconfig + supabase/.env.local written."
  else
    SKIPPED+=("iOS sync — run: MASTERMIND_SECRETS=$SECRETS_ENV bash $REPO/scripts/sync-secrets-from-mastermind.sh")
    warn "sync failed — do it by hand later (see summary)."
  fi
else
  SKIPPED+=("iOS sync — run: bash $REPO/scripts/sync-secrets-from-mastermind.sh")
fi

# ── Stage 5: Resend API key → web/.env.local ──────────────────────────────
ENV_FILE="$WEB_ENV"
stage "Resend — API key (mangasm.app waitlist)" 2
say "The waitlist form sends via Resend. Writing to:"
note "$WEB_ENV"
open_url "https://resend.com/api-keys"
step "Create API Key → name it → copy it (starts re_)."
ask_secret RESEND_API_KEY "Paste the Resend API key:"
write_env RESEND_API_KEY "$RESEND_API_KEY"

# ── Stage 6: Waitlist addresses (config, not secret) ──────────────────────
stage "Waitlist — from / notify addresses" 1
say "FROM must be on a Resend-verified domain (or onboarding@resend.dev to test)."
ask WAITLIST_FROM "Send waitlist mail FROM (e.g. hello@mangasm.app):"
ask WAITLIST_NOTIFY_TO "Notify new signups TO (your inbox):"
write_env WAITLIST_FROM "$WAITLIST_FROM"
write_env WAITLIST_NOTIFY_TO "$WAITLIST_NOTIFY_TO"

# ── Stage 7: Push web env to Vercel (action) ──────────────────────────────
stage "Push web env to Vercel (linked project)" 2
say "Sets the three web vars on the Vercel project linked in $REPO (production)."
warn "This writes to production — but the values are already saved in web/.env.local either way."
if command -v vercel >/dev/null 2>&1 && confirm "Push RESEND_API_KEY / WAITLIST_FROM / WAITLIST_NOTIFY_TO to Vercel now?"; then
  for pair in "RESEND_API_KEY=$RESEND_API_KEY" "WAITLIST_FROM=$WAITLIST_FROM" "WAITLIST_NOTIFY_TO=$WAITLIST_NOTIFY_TO"; do
    name="${pair%%=*}"; value="${pair#*=}"
    if printf '%s' "$value" | vercel env add "$name" production --cwd "$REPO" >/dev/null 2>&1; then
      printf '  %s✓ set%s Vercel %s (production)\n' "$GREEN" "$RESET" "$name"
    else
      SKIPPED+=("Vercel env $name (may already exist) — update via: vercel env rm $name production && vercel env add $name production")
      warn "couldn't add $name (may already exist) — see summary."
    fi
  done
  note "Redeploy the web project for the new env to take effect."
else
  SKIPPED+=("Vercel web env — set RESEND_API_KEY / WAITLIST_FROM / WAITLIST_NOTIFY_TO via 'vercel env add … production'")
fi
# ──────────────────────────────────────────────────────────────────────────

finish
